add get ticket, post ticket, and path ticket/tickedId endpoints
projekt-zespolowy-lab04-2020/backend pull request #20
Opened 2020-03-31 08:09 UTC by krzysztofMi

Endpoints:

**GET: /ticket?all=**
all = true returns all tickets if admin, all = false returns all current user's tickets

**POST: /ticket**
creating new tickets as current user. Json argument for this endpoint is ticket content

**PATH: /ticket/{tickedId**}
updating ticket if it is current user ticket or when logged user account type is admin

2020-03-31 08:52 UTC, kotcrab commented
Please run code formatter on your code. You can see the build is failing due to linter checksL
http://149.156.146.249:60001/jenkins/blue/organizations/jenkins/backend/detail/PR-20/1/pipeline

2020-03-31 11:43 UTC, kotcrab requested changes
Looks good! Just few comments. Please also update `api.yaml` with new endpoints.

https://github.com/projekt-zespolowy-lab04-2020/backend/blob/master/api/src/main/resources/webroot/api.yaml

Documentation:
https://swagger.io/docs/specification/basic-structure/

Online editor:
https://editor.swagger.io/

2020-03-31 11:43 UTC, kotcrab commented on api/src/main/kotlin/pl/edu/pk/backend/app/Routes.kt
> +    router.patch("/ticket/:ticketId").handler(::pathTicket)
Typo `patchTicket`?

2020-03-31 11:43 UTC, kotcrab commented on api/src/main/kotlin/pl/edu/pk/backend/controller/TicketController.kt
> +    }
Don't leave empty catch blocks and avoid using exceptions for normal control flow. 
You can rewrite this using:
```
ctx.queryParam("all").firstOrNull()?.toBoolean()
```

2020-03-31 11:43 UTC, kotcrab commented on api/src/main/kotlin/pl/edu/pk/backend/controller/TicketController.kt
> +      if (!ctx.checkCurrentUserHasRole(Role.Admin)) return
I recommend avoid using one line ifs.

2020-03-31 11:43 UTC, kotcrab commented on core/src/main/kotlin/pl/edu/pk/backend/model/Ticket.kt
> +        "user_" + ticket.author.id,
Use email here. I'll update API doc but every field with `user-1` etc. should be an email.

2020-03-31 11:43 UTC, kotcrab commented on core/src/main/kotlin/pl/edu/pk/backend/service/TicketService.kt
> +    return ticketRepository.getAllTickets().map { it.map { TicketDto.from(it) } }
Prefer to put map/compose on new line.

2020-03-31 11:44 UTC, kotcrab commented
Also don't worry about failing CI check `default — Build finished. ` that was a misconfiguration. Should be fixed now but will probably be applied after new commit or new PR.

2020-03-31 15:09 UTC, krzysztofMi commented on api/src/main/kotlin/pl/edu/pk/backend/app/Routes.kt
> +    router.patch("/ticket/:ticketId").handler(::pathTicket)
I thought that is path ;D

2020-03-31 20:36 UTC, kotcrab approved these changes

2020-03-31 20:36 UTC, kotcrab commented
Okay, you can merge this 👍

2020-04-01 05:41 UTC, merged

2020-04-01 16:35 UTC, kotcrab commented
I fixed few issues with api.yml, please validate in the online editor next time, looks good otherwise. You can start working on part two of #16 .