API refactor
projekt-zespolowy-lab04-2020/backend pull request #46
Opened 2020-05-16 12:22 UTC by marcinpiwko

Changed:

- GET/POST/PATCH/DELETE for non existing object Id as path param returns http status 404 instead 400 (NoSuchResourceException)

- POST/PATCH/DELETE with empty response body returns http status 204 instead 200 

- endpoints: 

GET /ticket -> /tickets
GET /ticket/{ticketId} -> /tickets/{ticketId}
POST /ticket -> /tickets
POST /ticket/{ticketId}/comment -> /tickets/{ticketId}/comments
PATCH /ticket/{ticketId} -> /tickets/{ticketId}

GET /trip/{tripId} -> /trips/{tripId}
GET /trip/{tripId}/comments -> /trips/{tripId}/comments
POST /trip -> /trips
POST /trip/{tripId}/comment -> /trips/{tripId}/comments
PATCH /trip/{tripId} -> /trips/{tripId}
PATCH /trip/{tripId}/comment/{commentId} -> /trips/{tripId}/comments/{commentId}

/user endpoints not changed cause they refer to logged in user

Swagger updated

2020-05-16 17:01 UTC, kotcrab requested changes

2020-05-16 17:01 UTC, kotcrab commented on core/src/main/kotlin/pl/edu/pk/backend/repository/TripCommentRepository.kt
> +        if ((ar.cause() as PgException).detail.contains("nie występuje")) {
Server has English locale so this won't work, use `code` instead https://vertx.io/docs/apidocs/io/vertx/pgclient/PgException.html#getCode--
Also you're casting it to PgException which might not be always the case, use `as?` or more checks with `is PgException`

2020-05-17 10:31 UTC, marcinpiwko commented
Done

2020-05-17 11:21 UTC, kotcrab approved these changes

2020-05-17 11:42 UTC, merged